// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDyZ6KZKxbPchl0CieY00-HHZi2Z4KFCgc',
    appId: '1:1058511507637:web:3d9c366e3bef12364c6efc',
    messagingSenderId: '1058511507637',
    projectId: 'sangdon-market-3ae08',
    authDomain: 'sangdon-market-3ae08.firebaseapp.com',
    storageBucket: 'sangdon-market-3ae08.appspot.com',
    measurementId: 'G-QPRRYJ6C4K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAoNqW6yNYsCvSL_G4sFWuRkWotWcdqxFU',
    appId: '1:1058511507637:android:13aab651f1fe77f54c6efc',
    messagingSenderId: '1058511507637',
    projectId: 'sangdon-market-3ae08',
    storageBucket: 'sangdon-market-3ae08.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzYeHUyJFlefM96Foua7Cy6LQD2oRjn8I',
    appId: '1:1058511507637:ios:964d5a623613cb924c6efc',
    messagingSenderId: '1058511507637',
    projectId: 'sangdon-market-3ae08',
    storageBucket: 'sangdon-market-3ae08.appspot.com',
    iosClientId: '1058511507637-oppoishdjjvuhmj2pdp5dtc8tss3o2dh.apps.googleusercontent.com',
    iosBundleId: 'com.sangdon.fastcampusMarket',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCzYeHUyJFlefM96Foua7Cy6LQD2oRjn8I',
    appId: '1:1058511507637:ios:6a9985bc0924e5a34c6efc',
    messagingSenderId: '1058511507637',
    projectId: 'sangdon-market-3ae08',
    storageBucket: 'sangdon-market-3ae08.appspot.com',
    iosClientId: '1058511507637-72137modp672qd7rrnggqojjm4v0mbgb.apps.googleusercontent.com',
    iosBundleId: 'com.sangdon.fastcampusMarket.RunnerTests',
  );
}
